apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJME1EWXhNakF6TlRZeU0xb1lEekl4TWpRd05URTVNRE0xTmpJeldqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCnlHYVZWSHlpSXpnTllzN0kzVUhxdUtyekpQb2p6VUphRVZCM1crcXZoZlVHUlpkSVkwLzdHb0xqbEJycFBGT1gKcTVnVk1KVUtqdUtQYWxsT0toLy82REZUU1RpaWtrcExpZW5tUlMxNlhUcGY4N1ZLck01TEh2VWdEMTZ2TTZ5QgoxM2dmNllJcGlmc0J5WEdKZ1hxU2tJa3FmNTZ1UjV3ZklSYlY4NkxvMnBYSnhLWk0vbFBiTXdiamFVMUNWS2RmCitkU1doNWxtTCtIMkpPdHNBWURxbTBnZmYvblNEeUtyWXRtUVZkd1hvYWlvNTF5T28veCt6OGFDdEdrUnc4TFIKUTFtRzREZTdkK3ByMDVLT29aRnZDZWh6Qjlkb0o3Y2pYVUd6SkI2d0tBajdwMjZaZi9BbFgxcm9sNEI0U21mQQpLdm0rR2VvQTA3ZHp0cmdCR2kvSXVRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVyWko5Y2dwTFZVdTQ3V1VkbGxVT3IyditlMXN3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFJNURRMExzMFZ4MnJ0am9kRmRCZFlta3lLTFpzVEJvWUpLM214SnJta21HV0JITwpWTURRb3hDcXdvM2VKWTlicHJHTm5hTFZoREF5eHJNeDNGS3doSVI5ekxnMnBSNm1jcUVZN3RkNnFRNmV2ZFA1CnVYT0pLV05YZHkzLzZCbUR0clo3OTIwaVQvakhHTEpaNDFCT2Q3a01mZFk5cjhaY0llL05JazVtTjN5VHllZUEKQSthV1Z0cklsT1ZRbG1sZ3FLbDh5d0h4UFcwWHpqODZnZmVvcW9xbUJabEdzY1dveXl5NE1sVXRNbnBzUTdWMQpJYjhsaUtzTEtKRnc1ZVkvaUpKU3BBMWRmN043SHFvcTVhL0pPSDFoT29tb1p6cEErbEt0OXcxbFhrZnNtZzZxCnRkcTN4V3dCTVhYbFhFMEVRNVhYS2xYYklRWlJkOEhMcVdHb1ROaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://fc030c28-e259-4c02-83c7-66b629bd33f5.kr.vnks.ntruss.com
  name: nks_kr_contest62-cluster_fc030c28-e259-4c02-83c7-66b629bd33f5
contexts:
- context:
    cluster: nks_kr_contest62-cluster_fc030c28-e259-4c02-83c7-66b629bd33f5
    user: nks_kr_contest62-cluster_fc030c28-e259-4c02-83c7-66b629bd33f5
  name: nks_kr_contest62-cluster_fc030c28-e259-4c02-83c7-66b629bd33f5
current-context: nks_kr_contest62-cluster_fc030c28-e259-4c02-83c7-66b629bd33f5
kind: Config
preferences: {}
users:
- name: nks_kr_contest62-cluster_fc030c28-e259-4c02-83c7-66b629bd33f5
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - --clusterUuid
      - fc030c28-e259-4c02-83c7-66b629bd33f5
      - --region
      - KR
      command: ncp-iam-authenticator
      env: null
      provideClusterInfo: false
